name: Build Android App

on:
  push:
    branches: [ main ]
    paths:
      - 'frontend/**'
      - '.github/workflows/build-android.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend

    steps:
    - uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'
        cache: 'npm'
        cache-dependency-path: './frontend/package-lock.json'

    - name: Install dependencies
      run: npm ci

    - name: Setup Android SDK
      uses: android-actions/setup-android@v2

    - name: Create .env file
      run: |
        echo "API_URL=${{ secrets.API_URL }}" > .env

    - name: Build Android Release
      run: |
        cd android
        ./gradlew assembleRelease

    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: app-release
        path: frontend/android/app/build/outputs/apk/release/app-release.apk 