name: Deploy Backend

on:
  push:
    branches: [ main ]
    paths:
      - 'backend/**'
      - '.github/workflows/deploy-backend.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Run tests
      run: |
        # Add test commands when tests are implemented
        echo "Running tests..."
    
    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v0
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true

    - name: Build and push Docker image
      run: |
        gcloud auth configure-docker
        docker build -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/sueohaja-backend:${{ github.sha }} .
        docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/sueohaja-backend:${{ github.sha }}

    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy sueohaja-backend \
          --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/sueohaja-backend:${{ github.sha }} \
          --platform managed \
          --region ${{ secrets.GCP_REGION }} \
          --allow-unauthenticated \
          --set-env-vars="MONGO_USER=${{ secrets.MONGO_USER }},MONGO_PASSWORD=${{ secrets.MONGO_PASSWORD }},MONGO_HOST=${{ secrets.MONGO_HOST }},MONGO_PORT=${{ secrets.MONGO_PORT }}"
      
    - name: Show deployed service URL
      run: |
        echo "Deployed to: $(gcloud run services describe sueohaja-backend --platform managed --region ${{ secrets.GCP_REGION }} --format 'value(status.url)')" 